services:
  db_mariadb:
    image: mariadb:lts
    container_name: mariadb_vistorias
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3300:3300"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: