// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaVistorias.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260702134955_AddCamposOriginaisVistoria")]
    partial class AddCamposOriginaisVistoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemaVistorias.Models.Ativo", b =>
                {
                    b.Property<string>("PatrimonioAgevap")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContratoGestao")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CaminhoFotos")
                        .HasColumnType("longtext");

                    b.Property<string>("ClassificacaoQualidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CondicaoFuncional")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CondicaoOriginal")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataVistoria")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InstalacaoEndereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InstalacaoOriginal")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAvulso")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NovoEstadoConservacao")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroLaudo")
                        .HasColumnType("longtext");

                    b.Property<string>("PatrimonioOrgaoGestor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PatrimonioOrgaoOriginal")
                        .HasColumnType("longtext");

                    b.Property<string>("UsuarioVistoriador")
                        .HasColumnType("longtext");

                    b.HasKey("PatrimonioAgevap", "ContratoGestao");

                    b.ToTable("Ativos");
                });

            modelBuilder.Entity("SistemaVistorias.Models.Sessao", b =>
                {
                    b.Property<string>("Token")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Token");

                    b.ToTable("Sessoes");
                });

            modelBuilder.Entity("SistemaVistorias.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
