// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaVistorias.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260626141545_InicializarTabelaAtivos")]
    partial class InicializarTabelaAtivos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemaVistorias.Models.Ativo", b =>
                {
                    b.Property<string>("PatrimonioAgevap")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContratoGestao")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CaminhoFotos")
                        .HasColumnType("longtext");

                    b.Property<string>("ClassificacaoQualidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CondicaoFuncional")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataVistoria")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("InstalacaoEndereco")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NovoEstadoConservacao")
                        .HasColumnType("longtext");

                    b.Property<string>("NumeroLaudo")
                        .HasColumnType("longtext");

                    b.Property<string>("PatrimonioOrgaoGestor")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("PatrimonioAgevap", "ContratoGestao");

                    b.ToTable("Ativos");
                });
#pragma warning restore 612, 618
        }
    }
}
